default_context:
  project_name: 'CandyDeliveryAPI'
  project_slug: 'candydeliveryapi'
  domain_main: 'candydeliveryapi.com'
  domain_staging: 'stag.candydeliveryapi.com'
  docker_swarm_stack_name_main: 'candydeliveryapi-com'
  docker_swarm_stack_name_staging: 'stag-candydeliveryapi-com'
  secret_key: '12345'
  first_superuser: 'admin@candydeliveryapi.com'
  first_superuser_password: '12345'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.candydeliveryapi.com", "https://stag.candydeliveryapi.com", "https://candydeliveryapi.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: '12345'
  smtp_emails_from_email: 'info@candydeliveryapi.com'
  postgres_password: '12345'
  pgadmin_default_user: '12345'
  pgadmin_default_user_password: '12345'
  traefik_constraint_tag: 'candydeliveryapi.com'
  traefik_constraint_tag_staging: 'stag.candydeliveryapi.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:12345'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
